import { AIRFRAME_PRESETS } from '../data/presets';
import { BF_DEFAULTS } from '../data/defaults';
import { hasDiffThrust } from '../data/validation';
import { pinToCli } from './timerCheck';

// Mixer name mapping
const MIXER_NAMES = {
  8: 'FLYING_WING',
  14: 'AIRPLANE',
  24: 'CUSTOMAIRPLANE',
};

export function generateCli({ preset, motors, servos, wingSettings, pids, rates, diffThrust, complexity, selectedTarget, assignments, tpaSettings, spaSettings, passthrough }) {
  const lines = [];
  const presetName = AIRFRAME_PRESETS[preset]?.name || preset;
  const imported = passthrough && Object.keys(passthrough).some(k => {
    const v = passthrough[k];
    return v && (Array.isArray(v) ? v.length > 0 : true);
  });

  lines.push('# Wing Mixer Configuration');
  lines.push(`# Preset: ${presetName}`);
  lines.push('# Generated by BF Wing Mixer Tool');
  lines.push('');
  lines.push('batch start');
  lines.push('');

  // Resource assignments (Expert with target, or imported resources)
  if (selectedTarget && assignments && Object.keys(assignments).length > 0) {
    lines.push(`# Resource assignment for ${selectedTarget.boardName}`);
    for (let i = 1; i <= 8; i++) lines.push(`resource MOTOR ${i} NONE`);
    for (let i = 1; i <= 4; i++) lines.push(`resource SERVO ${i} NONE`);
    lines.push('');

    const motorAssigns = [];
    const servoAssigns = [];
    for (const [pin, a] of Object.entries(assignments)) {
      if (a.type === 'motor') motorAssigns.push({ pin, index: a.index });
      else if (a.type === 'servo') servoAssigns.push({ pin, index: a.index });
    }
    motorAssigns.sort((a, b) => a.index - b.index);
    servoAssigns.sort((a, b) => a.index - b.index);

    for (const m of motorAssigns) lines.push(`resource MOTOR ${m.index} ${pinToCli(m.pin)}`);
    for (const s of servoAssigns) lines.push(`resource SERVO ${s.index} ${pinToCli(s.pin)}`);
    lines.push('');

    if (selectedTarget.uarts && selectedTarget.uarts.length > 0) {
      lines.push('# UART assignments \u2014 configure in Betaflight Ports tab:');
      for (const u of selectedTarget.uarts) {
        const tx = u.tx ? pinToCli(u.tx) : null;
        const rx = u.rx ? pinToCli(u.rx) : null;
        let desc;
        if (tx && rx) desc = `available (TX: ${tx}, RX: ${rx})`;
        else if (rx) desc = `RX only (RX: ${rx})`;
        else if (tx) desc = `TX only (TX: ${tx})`;
        else desc = 'no pins';
        lines.push(`# UART${u.index}: ${desc}`);
      }
      lines.push('');
    }
  } else if (imported && passthrough.resources?.length > 0) {
    // Imported resources — pass through verbatim
    lines.push('# resources');
    for (const r of passthrough.resources) {
      lines.push(`resource ${r.type} ${r.index} ${r.pin}`);
    }
    lines.push('');
  }

  // Features (pass-through from import)
  if (imported && passthrough.features?.length > 0) {
    lines.push('# feature');
    for (const f of passthrough.features) lines.push(`feature ${f}`);
    lines.push('');
  }

  // Serial (pass-through from import)
  if (imported && passthrough.serial?.length > 0) {
    lines.push('# serial');
    for (const s of passthrough.serial) {
      lines.push(`serial ${s.uart} ${s.functionMask} ${s.mspBaud} ${s.gpsBaud} ${s.telBaud} ${s.bbBaud}`);
    }
    lines.push('');
  }

  // Mixer type — use name not number
  const isCustom = motors.length > 1 || diffThrust;
  const mixerType = isCustom ? 'Custom Airplane' : (servos.length <= 2 ? 'Flying Wing' : 'Airplane');
  const mixerNum = isCustom ? 24 : (servos.length <= 2 ? 8 : 14);
  const mixerName = MIXER_NAMES[mixerNum] || 'CUSTOMAIRPLANE';
  lines.push(`# Mixer: ${mixerType}`);
  lines.push(`mixer ${mixerName}`);

  // Motor mix
  lines.push('mmix reset');
  motors.forEach((m, i) => {
    lines.push(`mmix ${i} ${m.throttle.toFixed(3)} ${m.roll.toFixed(3)} ${m.pitch.toFixed(3)} ${m.yaw.toFixed(3)}`);
  });
  lines.push('');

  // Servo endpoints (pass-through from import)
  if (imported && passthrough.servoConfig?.length > 0) {
    lines.push('# servo');
    for (const s of passthrough.servoConfig) {
      lines.push(`servo ${s.index} ${s.min} ${s.max} ${s.mid} ${s.rate} ${s.forwardChannel}`);
    }
    lines.push('');
  }

  // Servo mix — 8 fields: index servo source rate speed min max box
  lines.push('# servo mixer');
  lines.push('smix reset');
  let smixIdx = 0;
  servos.forEach((s) => {
    if (s.roll !== 0) {
      lines.push(`smix ${smixIdx} ${s.id} 0 ${s.roll} 0 0 100 0`);
      smixIdx++;
    }
    if (s.pitch !== 0) {
      lines.push(`smix ${smixIdx} ${s.id} 1 ${s.pitch} 0 0 100 0`);
      smixIdx++;
    }
    if (s.yaw !== 0) {
      lines.push(`smix ${smixIdx} ${s.id} 2 ${s.yaw} 0 0 100 0`);
      smixIdx++;
    }
  });
  lines.push('');

  // Pass-through: beacon, map, aux, rxrange
  if (imported) {
    if (passthrough.beacon?.length > 0) {
      lines.push('# beacon');
      for (const b of passthrough.beacon) lines.push(b);
      lines.push('');
    }
    if (passthrough.map) {
      lines.push('# map');
      lines.push(passthrough.map);
      lines.push('');
    }
    if (passthrough.aux?.length > 0) {
      lines.push('# aux');
      for (const a of passthrough.aux) lines.push(a);
      lines.push('');
    }
    if (passthrough.rxrange?.length > 0) {
      lines.push('# rxrange');
      for (const r of passthrough.rxrange) lines.push(r);
      lines.push('');
    }
  }

  // === MASTER CONTEXT ===
  const masterLines = [];

  // Differential thrust
  if (hasDiffThrust(motors)) {
    masterLines.push('set yaw_type = DIFF_THRUST');
  }

  // Servo PWM rate
  emitIfDiff(masterLines, 'servo_pwm_rate', wingSettings.servo_pwm_rate);

  // SPA modes are master context
  if (complexity === 'expert' && spaSettings) {
    emitIfDiff(masterLines, 'spa_roll_mode', spaSettings.spa_roll_mode);
    emitIfDiff(masterLines, 'spa_pitch_mode', spaSettings.spa_pitch_mode);
    emitIfDiff(masterLines, 'spa_yaw_mode', spaSettings.spa_yaw_mode);
  } else if (imported) {
    // When imported, always emit SPA modes if non-default
    emitIfDiff(masterLines, 'spa_roll_mode', spaSettings?.spa_roll_mode);
    emitIfDiff(masterLines, 'spa_pitch_mode', spaSettings?.spa_pitch_mode);
    emitIfDiff(masterLines, 'spa_yaw_mode', spaSettings?.spa_yaw_mode);
  }

  if (masterLines.length > 0) {
    lines.push('# master');
    lines.push(...masterLines);
    lines.push('');
  }

  // === PROFILE 0 ===
  if (complexity !== 'simple') {
    lines.push('profile 0');
    lines.push('');

    // PID tuning
    const pidLines = [];
    for (const axis of ['roll', 'pitch', 'yaw']) {
      for (const term of ['p', 'i', 'd', 'f']) {
        const key = `${term}_${axis}`;
        const value = pids[axis][term];
        if (String(value) !== String(BF_DEFAULTS[key])) {
          pidLines.push(`set ${key} = ${value}`);
        }
      }
    }
    if (pidLines.length > 0) {
      lines.push('# PID tuning');
      lines.push(...pidLines);
      lines.push('');
    }

    // S-term (profile context)
    if (complexity === 'expert' || imported) {
      const stermLines = [];
      emitIfDiff(stermLines, 's_roll', wingSettings.s_roll);
      emitIfDiff(stermLines, 's_pitch', wingSettings.s_pitch);
      emitIfDiff(stermLines, 's_yaw', wingSettings.s_yaw);
      if (stermLines.length > 0) {
        lines.push('# S-term');
        lines.push(...stermLines);
        lines.push('');
      }
    }

    // TPA airspeed curve (profile context)
    if ((complexity === 'expert' || imported) && tpaSettings) {
      const tpaLines = [];
      emitIfDiff(tpaLines, 'tpa_mode', tpaSettings.tpa_mode);
      emitIfDiff(tpaLines, 'tpa_curve_type', tpaSettings.tpa_curve_type);
      emitIfDiff(tpaLines, 'tpa_speed_max_voltage', tpaSettings.tpa_speed_max_voltage);
      emitIfDiff(tpaLines, 'tpa_speed_basic_delay', tpaSettings.tpa_speed_basic_delay);
      emitIfDiff(tpaLines, 'tpa_curve_stall_throttle', tpaSettings.tpa_curve_stall_throttle);
      emitIfDiff(tpaLines, 'tpa_curve_pid_thr0', tpaSettings.tpa_curve_pid_thr0);
      emitIfDiff(tpaLines, 'tpa_curve_pid_thr100', tpaSettings.tpa_curve_pid_thr100);
      emitIfDiff(tpaLines, 'tpa_curve_expo', tpaSettings.tpa_curve_expo);
      if (tpaLines.length > 0) {
        lines.push('# TPA airspeed curve');
        lines.push(...tpaLines);
        lines.push('');
      }
    }

    // SPA center/width (profile context)
    if ((complexity === 'expert' || imported) && spaSettings) {
      const spaLines = [];
      emitIfDiff(spaLines, 'spa_roll_center', spaSettings.spa_roll_center);
      emitIfDiff(spaLines, 'spa_roll_width', spaSettings.spa_roll_width);
      emitIfDiff(spaLines, 'spa_pitch_center', spaSettings.spa_pitch_center);
      emitIfDiff(spaLines, 'spa_pitch_width', spaSettings.spa_pitch_width);
      emitIfDiff(spaLines, 'spa_yaw_center', spaSettings.spa_yaw_center);
      emitIfDiff(spaLines, 'spa_yaw_width', spaSettings.spa_yaw_width);
      if (spaLines.length > 0) {
        lines.push('# Setpoint PID attenuation');
        lines.push(...spaLines);
        lines.push('');
      }
    }

    // Wing essentials (profile context, always for wings)
    const wingLines = [];
    emitIfDiff(wingLines, 'anti_gravity_gain', 0);
    emitIfDiff(wingLines, 'd_max_roll', 0);
    emitIfDiff(wingLines, 'd_max_pitch', 0);
    emitIfDiff(wingLines, 'iterm_relax_cutoff', wingSettings.iterm_relax_cutoff);
    emitIfDiff(wingLines, 'angle_earth_ref', 0);
    if (wingLines.length > 0) {
      lines.push('# Wing essentials');
      lines.push(...wingLines);
      lines.push('');
    }
  }

  // === RATEPROFILE 0 ===
  if (complexity !== 'simple') {
    const rateLines = [];
    emitIfDiff(rateLines, 'roll_rc_rate', rates.roll);
    emitIfDiff(rateLines, 'pitch_rc_rate', rates.pitch);
    emitIfDiff(rateLines, 'yaw_rc_rate', rates.yaw);

    if (rateLines.length > 0) {
      lines.push('rateprofile 0');
      lines.push('');
      lines.push('# Rates');
      lines.push(...rateLines);
      lines.push('');
    }
  }

  lines.push('batch end');
  lines.push('save');

  return lines.join('\n');
}

function emitIfDiff(lines, key, value) {
  if (value === undefined || value === null) return;
  if (String(value) !== String(BF_DEFAULTS[key])) {
    lines.push(`set ${key} = ${value}`);
  }
}
